name: metar_dart
description: Parse Meteorological Weather reports emited from aeronautical land stations (METAR). Coming soon TAF and SYNOP.
version: 0.2.1
repository: https://github.com/diego-garro/metar-dart
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http: ^0.12.2
  tuple: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
