name: metar_dart
description: Parse Meteorological Weather reports emited from aeronautical land stations (METAR). Coming soon TAF and SYNOP.
version: 0.3.1
repository: https://github.com/TAF-Verification/metar-dart
documentation: https://github.com/TAF-Verification/metar-dart/blob/main/doc/docs.md
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  http: ^0.13.5
  tuple: ^2.0.0

dev_dependencies:
  test: ^1.21.6
  coverage: ^1.6.1
  lints: ^2.0.0
