name: metar_dart
description: Parse Meteorological Weather reports emited from aeronautical land stations (METAR). Coming soon TAF and SYNOP.
version: 0.2.1
repository: https://github.com/TAF-Verification/metar-dart
documentation: https://github.com/TAF-Verification/metar-dart/blob/docs/docs/docs.md
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  http: ^0.13.5
  tuple: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.5
  coverage: ^1.6.0